using System.Collections.Generic;
using TileShop.Core;

namespace TileShop.Plugins
{
    /// <summary>
    /// Interface for implementing a plugin that can parse files and generate descriptions
    /// for arrangers and palettes
    /// </summary>
    public interface IFileParserContract
    {
        /// <summary>
        /// The host requests that the plugin displays its interface and generate arrangers and/or palette data
        /// </summary>
        /// <returns>True if there are arrangers or palettes generated for the host to receive</returns>
        bool DisplayPluginInterface();

        /// <summary>
        /// The host requests Resources that were generated by the plugin
        /// </summary>
        /// <returns></returns>
        Dictionary<string, IProjectResource> RetrieveResourceMap();
    }
}
